// Mocks generated by Mockito 5.4.4 from annotations
// in scoutmena_app/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i10;

import 'package:dartz/dartz.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:scoutmena_app/core/error/failures.dart' as _i6;
import 'package:scoutmena_app/features/authentication/domain/entities/user.dart'
    as _i7;
import 'package:scoutmena_app/features/authentication/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:scoutmena_app/features/coach_profile/domain/entities/coach_profile.dart'
    as _i20;
import 'package:scoutmena_app/features/coach_profile/domain/entities/team.dart'
    as _i21;
import 'package:scoutmena_app/features/coach_profile/domain/repositories/coach_repository.dart'
    as _i19;
import 'package:scoutmena_app/features/player_profile/domain/entities/player_photo.dart'
    as _i11;
import 'package:scoutmena_app/features/player_profile/domain/entities/player_profile.dart'
    as _i9;
import 'package:scoutmena_app/features/player_profile/domain/entities/player_stat.dart'
    as _i13;
import 'package:scoutmena_app/features/player_profile/domain/entities/player_video.dart'
    as _i12;
import 'package:scoutmena_app/features/player_profile/domain/repositories/player_repository.dart'
    as _i8;
import 'package:scoutmena_app/features/scout_profile/domain/entities/saved_search.dart'
    as _i18;
import 'package:scoutmena_app/features/scout_profile/domain/entities/scout_profile.dart'
    as _i15;
import 'package:scoutmena_app/features/scout_profile/domain/entities/search_filters.dart'
    as _i17;
import 'package:scoutmena_app/features/scout_profile/domain/entities/search_results.dart'
    as _i16;
import 'package:scoutmena_app/features/scout_profile/domain/repositories/scout_repository.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i5.User?>.empty(),
      ) as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, String>> signInWithPhone(
          String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPhone,
          [phoneNumber],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #signInWithPhone,
            [phoneNumber],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User>> verifyOTP({
    required String? verificationId,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [],
          {
            #verificationId: verificationId,
            #otp: otp,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User>>.value(
            _FakeEither_0<_i6.Failure, _i5.User>(
          this,
          Invocation.method(
            #verifyOTP,
            [],
            {
              #verificationId: verificationId,
              #otp: otp,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.User>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>> register({
    required String? firebaseUid,
    required Map<String, dynamic>? userData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #firebaseUid: firebaseUid,
            #userData: userData,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #firebaseUid: firebaseUid,
              #userData: userData,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>> loginWithFirebase() =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithFirebase,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(
            #loginWithFirebase,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [PlayerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerRepository extends _i1.Mock implements _i8.PlayerRepository {
  MockPlayerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>> getPlayerProfile(
          String? playerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayerProfile,
          [playerId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>>.value(
                _FakeEither_0<_i6.Failure, _i9.PlayerProfile>(
          this,
          Invocation.method(
            #getPlayerProfile,
            [playerId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>> createPlayerProfile(
          Map<String, dynamic>? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlayerProfile,
          [profileData],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>>.value(
                _FakeEither_0<_i6.Failure, _i9.PlayerProfile>(
          this,
          Invocation.method(
            #createPlayerProfile,
            [profileData],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>> updatePlayerProfile(
    String? playerId,
    Map<String, dynamic>? profileData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlayerProfile,
          [
            playerId,
            profileData,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>>.value(
                _FakeEither_0<_i6.Failure, _i9.PlayerProfile>(
          this,
          Invocation.method(
            #updatePlayerProfile,
            [
              playerId,
              profileData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i9.PlayerProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, String>> uploadProfilePhoto(
    String? playerId,
    _i10.File? photoFile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfilePhoto,
          [
            playerId,
            photoFile,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #uploadProfilePhoto,
            [
              playerId,
              photoFile,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i11.PlayerPhoto>>> getPlayerPhotos(
          String? playerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayerPhotos,
          [playerId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i11.PlayerPhoto>>>.value(
                _FakeEither_0<_i6.Failure, List<_i11.PlayerPhoto>>(
          this,
          Invocation.method(
            #getPlayerPhotos,
            [playerId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i11.PlayerPhoto>>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i11.PlayerPhoto>> uploadPlayerPhoto(
    String? playerId,
    _i10.File? photoFile, {
    String? caption,
    bool? isPrimary = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPlayerPhoto,
          [
            playerId,
            photoFile,
          ],
          {
            #caption: caption,
            #isPrimary: isPrimary,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i11.PlayerPhoto>>.value(
                _FakeEither_0<_i6.Failure, _i11.PlayerPhoto>(
          this,
          Invocation.method(
            #uploadPlayerPhoto,
            [
              playerId,
              photoFile,
            ],
            {
              #caption: caption,
              #isPrimary: isPrimary,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i11.PlayerPhoto>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deletePlayerPhoto(
    String? playerId,
    String? photoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlayerPhoto,
          [
            playerId,
            photoId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deletePlayerPhoto,
            [
              playerId,
              photoId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> reorderPlayerPhotos(
    String? playerId,
    List<Map<String, dynamic>>? photoOrder,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderPlayerPhotos,
          [
            playerId,
            photoOrder,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #reorderPlayerPhotos,
            [
              playerId,
              photoOrder,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i12.PlayerVideo>>> getPlayerVideos(
          String? playerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayerVideos,
          [playerId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i12.PlayerVideo>>>.value(
                _FakeEither_0<_i6.Failure, List<_i12.PlayerVideo>>(
          this,
          Invocation.method(
            #getPlayerVideos,
            [playerId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i12.PlayerVideo>>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i12.PlayerVideo>> uploadPlayerVideo(
    String? playerId,
    _i10.File? videoFile, {
    required String? title,
    String? description,
    String? videoType = r'highlight',
    _i10.File? thumbnailFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPlayerVideo,
          [
            playerId,
            videoFile,
          ],
          {
            #title: title,
            #description: description,
            #videoType: videoType,
            #thumbnailFile: thumbnailFile,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i12.PlayerVideo>>.value(
                _FakeEither_0<_i6.Failure, _i12.PlayerVideo>(
          this,
          Invocation.method(
            #uploadPlayerVideo,
            [
              playerId,
              videoFile,
            ],
            {
              #title: title,
              #description: description,
              #videoType: videoType,
              #thumbnailFile: thumbnailFile,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i12.PlayerVideo>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deletePlayerVideo(
    String? playerId,
    String? videoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlayerVideo,
          [
            playerId,
            videoId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deletePlayerVideo,
            [
              playerId,
              videoId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> reorderPlayerVideos(
    String? playerId,
    List<Map<String, dynamic>>? videoOrder,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderPlayerVideos,
          [
            playerId,
            videoOrder,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #reorderPlayerVideos,
            [
              playerId,
              videoOrder,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i13.PlayerStat>>> getPlayerStats(
          String? playerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayerStats,
          [playerId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i13.PlayerStat>>>.value(
                _FakeEither_0<_i6.Failure, List<_i13.PlayerStat>>(
          this,
          Invocation.method(
            #getPlayerStats,
            [playerId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i13.PlayerStat>>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i13.PlayerStat>> createPlayerStat(
    String? playerId,
    Map<String, dynamic>? statData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlayerStat,
          [
            playerId,
            statData,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i13.PlayerStat>>.value(
            _FakeEither_0<_i6.Failure, _i13.PlayerStat>(
          this,
          Invocation.method(
            #createPlayerStat,
            [
              playerId,
              statData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i13.PlayerStat>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i13.PlayerStat>> updatePlayerStat(
    String? playerId,
    String? statId,
    Map<String, dynamic>? statData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlayerStat,
          [
            playerId,
            statId,
            statData,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i13.PlayerStat>>.value(
            _FakeEither_0<_i6.Failure, _i13.PlayerStat>(
          this,
          Invocation.method(
            #updatePlayerStat,
            [
              playerId,
              statId,
              statData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i13.PlayerStat>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deletePlayerStat(
    String? playerId,
    String? statId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlayerStat,
          [
            playerId,
            statId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deletePlayerStat,
            [
              playerId,
              statId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [ScoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScoutRepository extends _i1.Mock implements _i14.ScoutRepository {
  MockScoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>> getScoutProfile(
          String? scoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoutProfile,
          [scoutId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>>.value(
                _FakeEither_0<_i6.Failure, _i15.ScoutProfile>(
          this,
          Invocation.method(
            #getScoutProfile,
            [scoutId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>> createScoutProfile(
          Map<String, dynamic>? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createScoutProfile,
          [profileData],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>>.value(
                _FakeEither_0<_i6.Failure, _i15.ScoutProfile>(
          this,
          Invocation.method(
            #createScoutProfile,
            [profileData],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>> updateScoutProfile(
    String? scoutId,
    Map<String, dynamic>? profileData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScoutProfile,
          [
            scoutId,
            profileData,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>>.value(
                _FakeEither_0<_i6.Failure, _i15.ScoutProfile>(
          this,
          Invocation.method(
            #updateScoutProfile,
            [
              scoutId,
              profileData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i15.ScoutProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, String>> uploadVerificationDocument(
          _i10.File? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadVerificationDocument,
          [document],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #uploadVerificationDocument,
            [document],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i16.SearchResults>> searchPlayers(
    _i17.SearchFilters? filters,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlayers,
          [
            filters,
            page,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i16.SearchResults>>.value(
                _FakeEither_0<_i6.Failure, _i16.SearchResults>(
          this,
          Invocation.method(
            #searchPlayers,
            [
              filters,
              page,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i16.SearchResults>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<String>>> getSearchSuggestions(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchSuggestions,
          [query],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, List<String>>>.value(
            _FakeEither_0<_i6.Failure, List<String>>(
          this,
          Invocation.method(
            #getSearchSuggestions,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i18.SavedSearch>>> getSavedSearches(
          String? scoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedSearches,
          [scoutId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i18.SavedSearch>>>.value(
                _FakeEither_0<_i6.Failure, List<_i18.SavedSearch>>(
          this,
          Invocation.method(
            #getSavedSearches,
            [scoutId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i18.SavedSearch>>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i18.SavedSearch>> createSavedSearch(
    String? scoutId,
    Map<String, dynamic>? searchData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSavedSearch,
          [
            scoutId,
            searchData,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i18.SavedSearch>>.value(
                _FakeEither_0<_i6.Failure, _i18.SavedSearch>(
          this,
          Invocation.method(
            #createSavedSearch,
            [
              scoutId,
              searchData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i18.SavedSearch>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deleteSavedSearch(
          String? searchId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSavedSearch,
          [searchId],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteSavedSearch,
            [searchId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i16.SearchResults>> executeSavedSearch(
    String? searchId,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeSavedSearch,
          [
            searchId,
            page,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i16.SearchResults>>.value(
                _FakeEither_0<_i6.Failure, _i16.SearchResults>(
          this,
          Invocation.method(
            #executeSavedSearch,
            [
              searchId,
              page,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i16.SearchResults>>);
}

/// A class which mocks [CoachRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoachRepository extends _i1.Mock implements _i19.CoachRepository {
  MockCoachRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>> getCoachProfile(
          String? coachId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoachProfile,
          [coachId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>>.value(
                _FakeEither_0<_i6.Failure, _i20.CoachProfile>(
          this,
          Invocation.method(
            #getCoachProfile,
            [coachId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>> createCoachProfile(
          Map<String, dynamic>? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCoachProfile,
          [profileData],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>>.value(
                _FakeEither_0<_i6.Failure, _i20.CoachProfile>(
          this,
          Invocation.method(
            #createCoachProfile,
            [profileData],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>> updateCoachProfile(
    String? coachId,
    Map<String, dynamic>? profileData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCoachProfile,
          [
            coachId,
            profileData,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>>.value(
                _FakeEither_0<_i6.Failure, _i20.CoachProfile>(
          this,
          Invocation.method(
            #updateCoachProfile,
            [
              coachId,
              profileData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i20.CoachProfile>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i21.Team>>> getCoachTeams(
          String? coachId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoachTeams,
          [coachId],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, List<_i21.Team>>>.value(
            _FakeEither_0<_i6.Failure, List<_i21.Team>>(
          this,
          Invocation.method(
            #getCoachTeams,
            [coachId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i21.Team>>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i21.Team>> createTeam(
    String? coachId,
    Map<String, dynamic>? teamData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTeam,
          [
            coachId,
            teamData,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i21.Team>>.value(
            _FakeEither_0<_i6.Failure, _i21.Team>(
          this,
          Invocation.method(
            #createTeam,
            [
              coachId,
              teamData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i21.Team>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i21.Team>> updateTeam(
    String? coachId,
    String? teamId,
    Map<String, dynamic>? teamData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeam,
          [
            coachId,
            teamId,
            teamData,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i21.Team>>.value(
            _FakeEither_0<_i6.Failure, _i21.Team>(
          this,
          Invocation.method(
            #updateTeam,
            [
              coachId,
              teamId,
              teamData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i21.Team>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deleteTeam(
    String? coachId,
    String? teamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTeam,
          [
            coachId,
            teamId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteTeam,
            [
              coachId,
              teamId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i21.Team>> addPlayerToTeam(
    String? coachId,
    String? teamId,
    String? playerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPlayerToTeam,
          [
            coachId,
            teamId,
            playerId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i21.Team>>.value(
            _FakeEither_0<_i6.Failure, _i21.Team>(
          this,
          Invocation.method(
            #addPlayerToTeam,
            [
              coachId,
              teamId,
              playerId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i21.Team>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i21.Team>> removePlayerFromTeam(
    String? coachId,
    String? teamId,
    String? playerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePlayerFromTeam,
          [
            coachId,
            teamId,
            playerId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i21.Team>>.value(
            _FakeEither_0<_i6.Failure, _i21.Team>(
          this,
          Invocation.method(
            #removePlayerFromTeam,
            [
              coachId,
              teamId,
              playerId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i21.Team>>);
}
